export const GET_STUDENT_DETAILS_REQUEST = "GET_STUDENT_DETAILS_REQUEST";
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_DETAILS_SUCCESS";
export const GET_STUDENT_DETAILS_FAIL = "GET_STUDENT_DETAILS_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";
